### ISSUE TITLE
Could not initialize random number generator

### ISSUE THREAD

**Issue by DarthDestroyer** [bitnami/bitnami-docker-apache#106]
**Description**

Container does not start and prints following Error:
(38)Function not implemented: AH00141: Could not initialize random number generator

**Steps to reproduce the issue:**

1. Use a Docker Host with Kernel 3.10.105
2. Add Container (2.4 and 2.4.43 tested)
3. Try to start it

**Describe the results you received:**

It stops with a critical Error

**Version**

- Output of `docker version`:

```
Version:          20.10.3
```

- Output of `docker info`:

```
 Kernel Version: 3.10.105
 Operating System:  (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.718GiB
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.28.5, build 1bbbad71
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Host is a Synology DS916+

**Comment by rafariossaa** [comment]
Hi,
  This issue is related to the kernel in the NAS.
  Could you take a look to this other issue ? https://github.com/bitnami/bitnami-docker-moodle/issues/111

**Comment by DarthDestroyer** [comment]
@rafariossaa Yeah, that was my first Step to read that - Looks like a Problem with Apache...
Had seen some other Threads where they talked about that and afaik, there is no way to update the kernel!
To be fair, there is ONE Method, but it is highly risky and i will not do that to run a docker container!

The thing with this Issue (https://github.com/bitnami/bitnami-docker-moodle/issues/111) is, that they are swithing Systems and Configs... Someone is talking about a SynoNAS and the rest is talking about all other variants of linux!

Points i've found:
https://www.reddit.com/r/synology/comments/j5770x/apache_rng_error_any_help/
https://community.synology.com/enu/forum/36/post/141509

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing those links .
  Could you share how did you get it working ?

**Comment by DarthDestroyer** [comment]
Hey!

Yeah, i've tried some Versions out. Version 2.4.38 seems to be compiled without the need of Kernel random Number Gen or whatever its called correctly!
I've tried also the httpd image and it seems to work without that Kernel module (or with another random approach)

so, i would say that that "problem" seems to be on your side...

**Comment by rafariossaa** [comment]
Hi,
  I am creating an internal task to look if something can be done in our side.
  I haven't checked the source, but that kernel function is needed because it produce better quality random numbers. Maybe there is a way to indicate other random number source, but I can not promise anything.

**Comment by mosesdd** [comment]
@DarthDestroyer I can reproduce this issue on a Synology RS3617xs with DSM 6.2.4-25556. On a DS1618+ with DSM 7.0-41890 it is working fine. So there is hope that if you update to DSM 7 the issue will be gone.
BTW, I came here because I got the same issue with the latest nextcloud image

**Comment by randradas** [comment]
Thank you @mosesdd for the information.

**Comment by rafariossaa** [comment]
Hi,
  Could you try the latest release of the image ?, it should fix this issue when using older kernels.

**Comment by Oryon007** [comment]
Hi @rafariossaa, 

I have the same SynoNAS as @DarthDestroyer with DSM 7.0-41890. I just pulled the latest release of NextCloud and am still getting the "`(38)Function not implemented: AH00141: Could not initialize random number generator`" error. 

- `docker version` Output:
`Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        b455053
 Built:             Mon Jun 21 02:03:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       a3bc36f
  Built:            Mon Jun 21 02:05:07 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00`
    
- `docker info` Output:
  `Kernel Version: 3.10.108
 Operating System:  (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4`
 
 - `docker-compose version`
  `docker-compose version 1.28.5, build 324b023a
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019`

**Comment by rafariossaa** [comment]
Hi,
  Can you indicate which kernel are you running ?.

**Comment by Oryon007** [comment]
> Hi,
> Can you indicate which kernel are you running ?.

Sure, it's `3.10.108`.

**Comment by rafariossaa** [comment]
Do you mind trying the apache container and check if you have the same issue ?

**Comment by Oryon007** [comment]
> Do you mind trying the apache container and check if you have the same issue ?

Sure. Let me see what I can do. It may take me up to a few days due to my current work schedule, but I'll update you as soon as I can.

**Comment by Oryon007** [comment]
Ok I lied....lol....I just quickly busted it out and tried it. :)

I used the `nextcloud:22.1.1-apache` container image and I'm still getting the same error:

```
[Tue Sep 28 09:41:43.331053 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

[Tue Sep 28 09:41:52.302537 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

[Tue Sep 28 09:42:03.995909 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

[Tue Sep 28 09:42:11.798666 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

[Tue Sep 28 09:42:20.630693 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

[Tue Sep 28 09:42:29.698390 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator
```

**Comment by rafariossaa** [comment]
Sorry, I should have indicated exactly which apache image.

I would like you to try: `docker run --name apache bitnami/apache:latest`

**Comment by Oryon007** [comment]
Looks like it's running so far:

```
apache 14:05:22.27
apache 14:05:22.28 Welcome to the Bitnami apache container
apache 14:05:22.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-apache
apache 14:05:22.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-apache/issues
apache 14:05:22.29
apache 14:05:22.30 INFO  ==> ** Starting Apache setup **
apache 14:05:22.96 INFO  ==> ** Apache setup finished! **

apache 14:05:23.06 INFO  ==> ** Starting Apache **
[Wed Sep 29 14:05:25.328459 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Sep 29 14:05:25.373634 2021] [ssl:warn] [pid 1] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Wed Sep 29 14:05:25.813731 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.49 (Unix) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Sep 29 14:05:25.813813 2021] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

**Comment by rafariossaa** [comment]
> I used the nextcloud:22.1.1-apache container image and I'm still getting the same error:
  We don't own that image, but we do have [owncloud](https://github.com/bitnami/bitnami-docker-owncloud) and it should work in your system. Just in case you want to try it.
